//Console.WriteLine("Введите числа А и В: ");
//Console.Write("A= ");
//int numberA = Console.ReadLine();
//Console.Write("B= ");
//int numberB = Console.ReadLine();
int numberA = new Random().Next(1, 20);
int numberB = new Random().Next(1, 20);
Console.Write("Число A = ");
Console.WriteLine(numberA);
Console.Write("Число B = ");
Console.WriteLine(numberB);
Console.Write("Сумма А и В = ");
Console.WriteLine(numberA + numberB);